import { Injectable } from '@angular/core';
import { Project, SDGScore } from '../models/project.models';

@Injectable({
  providedIn: 'root',
})
export class WorldBankDataService {
  getWorldBankProjects(): Project[] {
    return [
      {
        id: 1,
        projectTitle: 'Rural Development and Climate Resilience Project',
        country: 'Bangladesh',
        projectId: 'P173456',
        commitmentAmount: 250000000,
        status: 'Active',
        approvalDate: '2023-03-15',
        lastUpdatedDate: '2024-09-10',
        lastStageReached: 'Implementation',
        projectManagerId: 1,
        projectManager: {
          id: 1,
          username: 'john.doe',
          email: 'john.doe@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 1,
            sdgTitle: 'No Poverty',
            score: 85,
            description: 'Significant poverty reduction in target areas',
          },
          {
            sdgNumber: 2,
            sdgTitle: 'Zero Hunger',
            score: 78,
            description: 'Improved food security and nutrition',
          },
          {
            sdgNumber: 13,
            sdgTitle: 'Climate Action',
            score: 92,
            description: 'Strong climate resilience measures implemented',
          },
          {
            sdgNumber: 15,
            sdgTitle: 'Life on Land',
            score: 88,
            description: 'Biodiversity conservation and sustainable land use',
          },
        ],
      },
      {
        id: 2,
        projectTitle: 'Urban Water and Sanitation Improvement',
        country: 'India',
        projectId: 'P174789',
        commitmentAmount: 180000000,
        status: 'Active',
        approvalDate: '2023-06-20',
        lastUpdatedDate: '2024-09-05',
        lastStageReached: 'Implementation',
        projectManagerId: 2,
        projectManager: {
          id: 2,
          username: 'sarah.smith',
          email: 'sarah.smith@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 6,
            sdgTitle: 'Clean Water and Sanitation',
            score: 95,
            description: 'Excellent water infrastructure development',
          },
          {
            sdgNumber: 11,
            sdgTitle: 'Sustainable Cities',
            score: 82,
            description: 'Urban development with sustainability focus',
          },
          {
            sdgNumber: 3,
            sdgTitle: 'Good Health and Well-being',
            score: 89,
            description: 'Improved public health outcomes',
          },
        ],
      },
      {
        id: 3,
        projectTitle: 'Education for All Initiative',
        country: 'Kenya',
        projectId: 'P175123',
        commitmentAmount: 120000000,
        status: 'Closed',
        approvalDate: '2022-09-10',
        lastUpdatedDate: '2024-08-15',
        lastStageReached: 'Completion',
        projectManagerId: 3,
        projectManager: {
          id: 3,
          username: 'mike.johnson',
          email: 'mike.johnson@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 4,
            sdgTitle: 'Quality Education',
            score: 91,
            description: 'Outstanding educational outcomes achieved',
          },
          {
            sdgNumber: 5,
            sdgTitle: 'Gender Equality',
            score: 87,
            description: 'Strong gender parity in education',
          },
          {
            sdgNumber: 10,
            sdgTitle: 'Reduced Inequalities',
            score: 83,
            description: 'Reduced educational disparities',
          },
        ],
      },
      {
        id: 4,
        projectTitle: 'Renewable Energy Transition Program',
        country: 'Brazil',
        projectId: 'P176456',
        commitmentAmount: 320000000,
        status: 'Active',
        approvalDate: '2024-01-15',
        lastUpdatedDate: '2024-09-12',
        lastStageReached: 'Implementation',
        projectManagerId: 4,
        projectManager: {
          id: 4,
          username: 'emma.wilson',
          email: 'emma.wilson@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 7,
            sdgTitle: 'Affordable and Clean Energy',
            score: 94,
            description: 'Exceptional renewable energy deployment',
          },
          {
            sdgNumber: 13,
            sdgTitle: 'Climate Action',
            score: 96,
            description: 'Major contribution to climate goals',
          },
          {
            sdgNumber: 8,
            sdgTitle: 'Decent Work and Economic Growth',
            score: 79,
            description: 'Job creation in green economy',
          },
        ],
      },
      {
        id: 5,
        projectTitle: 'Maternal and Child Health Program',
        country: 'Nigeria',
        projectId: 'P177789',
        commitmentAmount: 95000000,
        status: 'Active',
        approvalDate: '2023-11-08',
        lastUpdatedDate: '2024-09-08',
        lastStageReached: 'Implementation',
        projectManagerId: 5,
        projectManager: {
          id: 5,
          username: 'david.brown',
          email: 'david.brown@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 3,
            sdgTitle: 'Good Health and Well-being',
            score: 88,
            description: 'Significant health improvements',
          },
          {
            sdgNumber: 5,
            sdgTitle: 'Gender Equality',
            score: 85,
            description: 'Enhanced maternal health services',
          },
          {
            sdgNumber: 1,
            sdgTitle: 'No Poverty',
            score: 72,
            description: 'Health access for vulnerable populations',
          },
        ],
      },
      {
        id: 6,
        projectTitle: 'Digital Infrastructure Development',
        country: 'Indonesia',
        projectId: 'P178123',
        commitmentAmount: 150000000,
        status: 'Pipeline',
        approvalDate: '2024-10-01',
        lastUpdatedDate: '2024-09-15',
        lastStageReached: 'Preparation',
        projectManagerId: 6,
        projectManager: {
          id: 6,
          username: 'lisa.garcia',
          email: 'lisa.garcia@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 9,
            sdgTitle: 'Industry, Innovation and Infrastructure',
            score: 76,
            description: 'Digital infrastructure development',
          },
          {
            sdgNumber: 8,
            sdgTitle: 'Decent Work and Economic Growth',
            score: 81,
            description: 'Technology sector job creation',
          },
          {
            sdgNumber: 4,
            sdgTitle: 'Quality Education',
            score: 68,
            description: 'Digital literacy improvements',
          },
        ],
      },
      {
        id: 7,
        projectTitle: 'Marine Conservation and Blue Economy',
        country: 'Philippines',
        projectId: 'P179456',
        commitmentAmount: 75000000,
        status: 'Active',
        approvalDate: '2023-08-22',
        lastUpdatedDate: '2024-09-06',
        lastStageReached: 'Implementation',
        projectManagerId: 7,
        projectManager: {
          id: 7,
          username: 'carlos.rodriguez',
          email: 'carlos.rodriguez@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 14,
            sdgTitle: 'Life Below Water',
            score: 93,
            description: 'Excellent marine conservation results',
          },
          {
            sdgNumber: 8,
            sdgTitle: 'Decent Work and Economic Growth',
            score: 77,
            description: 'Sustainable blue economy development',
          },
          {
            sdgNumber: 12,
            sdgTitle: 'Responsible Consumption and Production',
            score: 84,
            description: 'Sustainable fishing practices',
          },
        ],
      },
      {
        id: 8,
        projectTitle: 'Gender Equality and Women Empowerment',
        country: 'Morocco',
        projectId: 'P180789',
        commitmentAmount: 65000000,
        status: 'Closed',
        approvalDate: '2022-12-05',
        lastUpdatedDate: '2024-07-20',
        lastStageReached: 'Completion',
        projectManagerId: 8,
        projectManager: {
          id: 8,
          username: 'fatima.hassan',
          email: 'fatima.hassan@worldbank.org',
        },
        sdgScores: [
          {
            sdgNumber: 5,
            sdgTitle: 'Gender Equality',
            score: 90,
            description: 'Outstanding gender equality achievements',
          },
          {
            sdgNumber: 8,
            sdgTitle: 'Decent Work and Economic Growth',
            score: 86,
            description: 'Women economic empowerment',
          },
          {
            sdgNumber: 4,
            sdgTitle: 'Quality Education',
            score: 88,
            description: 'Girls education improvements',
          },
        ],
      },
    ];
  }

  getSDGColors(): { [key: number]: string } {
    return {
      1: '#E5243B',
      2: '#DDA63A',
      3: '#4C9F38',
      4: '#C5192D',
      5: '#FF3A21',
      6: '#26BDE2',
      7: '#FCC30B',
      8: '#A21942',
      9: '#FD6925',
      10: '#DD1367',
      11: '#FD9D24',
      12: '#BF8B2E',
      13: '#3F7E44',
      14: '#0A97D9',
      15: '#56C02B',
      16: '#00689D',
      17: '#19486A',
    };
  }
}
